### ISSUE TITLE
Unable to make a selection in console as arrow keys are not registered

### ISSUE THREAD

**Issue by johnstrickermayo** [pulumi/examples#322] opened 2019-06-20 21:06 UTC
I'm working in a bash 4 terminal on a new MacBook pro :
When running 'pulumi up', I'm unable to make a selection via the arrow keys:

```Do you want to perform this update?
  yes
> no
  details
error: confirmation cancelled, not proceeding with the update: Unknown Escape Sequence: ['\x1b' '[' '1']```

**Comment by ellismg** [comment] 2019-06-20 21:41
@johnstrickermayo

Thanks for opening this, this is unexpected, and I'm going to try to reproduce this and fix it.  In the interm, I believe you can pass `--yes` to `pulumi up` to accept the changes.  You can also explicitly run the preview step and exit by running `pulumi preview`

To help me reproduce the issue a few questions questions:

1. What version of the Pulumi CLI do you have installed (`pulumi version` will tell you)
2. Are you using the default `Terminal.app` that comes with macOS, or a different terminal emulator?
3. What version of macOS are you on?
4. What is the output of `echo $TERM` in your terminal where you are trying to run Pulumi?

**Comment by johnstrickermayo** [comment] 2019-06-21 12:34
@ellismg 
1. pulumi version v0.17.17
2. its the default terminal, I did upgrade bash from what came installed, so its version 5.0.7(1)-release (x86_64-apple-darwin18.5.0)
3. Mojave Version 10.14.5
4. xterm-256color

**Comment by johnstrickermayo** [comment] 2019-06-21 12:43
@ellismg so it looks like it may be bash related, when I switch over to zsh, It works fine

**Comment by johnstrickermayo** [comment] 2019-06-21 12:57
and when I switch back to bash 3.2, it also works fine

**Comment by johnstrickermayo** [comment] 2019-06-21 15:05
@ellismg Now I'm confused, when I switch back to the new version of bash things are now working fine: meaning I can no longer repo the problem. Feel free to close this issue & apologies for the runaround.

**Comment by joeduffy** [comment] 2019-06-21 15:14
I've seen this before, and now I feel bad because I meant to file an issue but apparently didn't. There was some program that, if I ran it, this same thing would happen, deterministically, every time (bash 3.2). I had to close and reopen the terminal to clear the issue (so clearly some terminal-wide state change had happened). I thought it was `docker` that I was running, but I just tried it, and no luck.

Is it possible there's a command you are running that gets the terminal into this state?

**Comment by johnstrickermayo** [comment] 2019-06-21 15:16
that sounds possible, I was in the process of setting up a new machine so I had done a whole bunch of things in a single session.

**Comment by pgavlin** [comment] 2019-09-06 23:39
I wonder if running `reset` in the problematic terminal would fix this issue.

For now, I'm going to close this as we no longer have a repro.

**Closed by pgavlin** 2019-09-06 23:39 UTC

**Comment by matt-newcombe** [comment] 2023-04-23 10:04
I know this issue is closed, but I just ran into this with a fresh install of latest pulumi. I can confirm that running `reset` in terminal (zsh) does indeed fix the issue
