### ISSUE TITLE
aws-ts-eks example failing

### ISSUE THREAD

**Issue by leezen** [pulumi/examples#1146] opened 2022-01-05 17:29 UTC
The `aws-ts-eks` example is failing due to the inability to acquire the `eks` plugin for some reason. I am able to reproduce this locally against v3.21.0 (and even earlier) versions of the CLI. Manual plugin acquisition (via `pulumi plugin install`) works around the issue, but it's unclear what's changed in either the CLI or the EKS package given this test was successful a couple days ago.

**Comment by justinvp** [comment] 2022-01-06 16:21
This isn't a regression in Pulumi. It's happening because of a recent change in the npm `resolve` package, which `@pulumi/pulumi` and `@pulumi/aws` depend on:

```
$ npm ls resolve
proj@ /proj
├─┬ @pulumi/eks@0.36.0
│ └─┬ @pulumi/aws@4.33.1
│   └── resolve@1.21.0 
└─┬ @pulumi/pulumi@3.21.0
  └─┬ normalize-package-data@2.5.0
    └── resolve@1.21.0  deduped
```

The problem was introduced in [this commit](https://github.com/browserify/resolve/commit/d6e08717a45f97df3fb14461f5601e9e0a0c5a03) 8 days ago, which was released in [`v1.21.0`](https://github.com/browserify/resolve/releases/tag/v1.21.0) 3 days ago.

That commit adds a test with an invalid `package.json`, which is included inside the published `resolve` package. Specifically this file: https://github.com/browserify/resolve/blob/main/test/resolver/malformed_package_json/package.json

When the `pulumi-language-nodejs` language host looks for plugins needed for the program, it recurses through `node_modules` reading all the `package.json` files it can find to determine which plugins are needed. It does find all the plugins (including eks), but it errors when reading the malformed `package.json` from the `resolve` library, and because of that, returns a null array of required plugins, so the `eks` plugin does not get installed.

Note that the `aws`, `docker`, and `kubernetes` plugins _are_ installed for the test because the associated npm packages include the `install-pulumi-plugin.js` script, which runs `pulumi plugin install resource <plugin> <version>` as part of installing each package. But the `@pulumi/eks` package does not have that script included yet (https://github.com/pulumi/pulumi-eks/issues/485) -- we currently rely on the language host reporting the plugin is required for it to get installed as part of running an update.

I think we'll want to address this in two ways:

1. Change the nodejs language host to be more resilient to errors reading malformed `package.json` files when trying to determine required plugins
2. Update the `@pulumi/eks` package to include the installer script that runs `pulumi plugin install` as part of installing the package (https://github.com/pulumi/pulumi-eks/issues/485)

**Comment by justinvp** [comment] 2022-01-06 21:42
The change to the lang host: https://github.com/pulumi/pulumi/pull/8699

**Comment by stack72** [comment] 2022-01-10 12:51
confirmed fixed in latest cron - thanks @justinvp

**Closed by stack72** 2022-01-10 12:51 UTC
Labels: kind/bug, resolution/fixed, p1
