### ISSUE TITLE
Error while adding --refresh to Python provisioning example

### ISSUE THREAD

**Issue by celinegoerke** [pulumi/examples#692] opened 2020-05-29 10:23 UTC
Hey! 

**What happened:**

I took the Python provisioning example (#675), ran it with `pulumi up` and everything worked as expected. Then I changed the name of a resource, did `pulumi up --refresh` and got an error:

`  pulumi-python:dynamic:Resource (cat-config):
    error: Preview failed: Exception calling application: Can't get attribute 'RemoteExecProvider' on <module 'provisioners' from '/home/celine/PycharmProjects/Provisioners/aws-py-ec2-provisioners/provisioners.py'>
`

**What did I expect to happen?**

Not getting any errors and refreshing my stacks as intended when using "refresh".

**How to reproduce:**

- Follow the instructions of the provisioning example for python (as described in the README.md)
- Change the name of a resource - for example instead of "cat_config" write "cat_config_test" in line 70 and change it in line 79 as well to match it
- Do either `pulumi up --refresh` or `pulumi refresh` and you will be getting the same error as I did

**Further information:**

When I tried to do the exact same thing with the TypeScript example (#191) it worked without any errors. 
I'm on Ubuntu 18.04.4 LTS, using PyCharm Professional 2020.1, Python 3.6 and Pulumi 2.3.0 (didn't work on Pulumi 2.2.1 as well)

**Comment by cloudspeak** [comment] 2020-10-23 21:28
Did you ever resolve this?  I am having the same issue, although it doesn't seem to be caused by a name change.

**Comment by GabrielZabielski** [comment] 2021-03-16 06:15
Hi, I have the same issue. 
Environment: newest Pulumi version (2.22.0), python 3.8, and Centos 7.8. I'm logging in with s3 bucket.

I have ~20 custom resources and each preview with refresh contains 1-5 randomly affected custom resources.

**Comment by lukehoban** [comment] 2021-06-16 06:37
This and https://github.com/pulumi/pulumi/issues/5621 appear to be tracking the same issue.  Closing this one out as a dupe since the other has additional upvotes, and the issue is likely to be in the core pulumi SDK, not just in the example.

**Closed by lukehoban** 2021-06-16 06:37 UTC
Labels: kind/bug, resolution/duplicate
