### ISSUE TITLE
eks-hello-world not working

### ISSUE THREAD

**Issue by badaljain** [pulumi/examples#1269] opened 2022-08-27 08:06 UTC
### What happened?

when running `pulumi up`:

```
  pulumi:pulumi:Stack (eks-hello-dev):
    error: Running program '/Users/bads/workspace/eks-hello' failed with an unhandled exception:
    TypeError: Invalid Version: null
        at new SemVer (/Users/bads/workspace/eks-hello/node_modules/@pulumi/eks/node_modules/semver/classes/semver.js:19:13)
        at Object.major (/Users/bads/workspace/eks-hello/node_modules/@pulumi/eks/node_modules/semver/functions/major.js:2:29)
        at Object.assertCompatibleAWSCLIExists (/Users/bads/workspace/eks-hello/node_modules/@pulumi/dependencies.ts:64:20)
        at createCore (/Users/bads/workspace/eks-hello/node_modules/@pulumi/cluster.ts:356:5)
        at new Cluster (/Users/bads/workspace/eks-hello/node_modules/@pulumi/cluster.ts:1431:22)
        at Object.<anonymous> (/Users/bads/workspace/eks-hello/index.ts:10:17)
        at Module._compile (node:internal/modules/cjs/loader:1105:14)
        at Module.m._compile (/Users/bads/workspace/eks-hello/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/bads/workspace/eks-hello/node_modules/ts-node/src/index.ts:442:12)
```

### Steps to reproduce

follow the eks-hello-world tutorial (https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/eks/)and run pulumi up

### Expected Behavior

should create eks cluster in aws

### Actual Behavior

the above error as pasted

### Output of `pulumi about`

$ pulumi about
CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.13.0
docker      3.4.1
eks         0.41.2
kubernetes  3.21.0
nodejs      unknown

Host     
OS       darwin
Version  11.6.8
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v16.16.0'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/badaljain
User           badaljain
Organizations  badaljain

Dependencies:
NAME                VERSION
@pulumi/aws         5.13.0
@pulumi/awsx        0.40.0
@pulumi/eks         0.41.2
@pulumi/kubernetes  3.21.0
@pulumi/pulumi      3.38.0
@types/node         14.18.26

Pulumi locates its logs in /var/folders/xj/k0tbd2092fbb7fmhyzcvr_rh0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment] 2022-08-30 11:58
Hi @badaljain 

I am going to close this as a duplicate of https://github.com/pulumi/pulumi-eks/issues/768

We can track the fix there - thanks so much for opening this

Paul

**Closed** 2022-08-30 11:58 UTC
Labels: kind/bug, resolution/duplicate
