### ISSUE TITLE
Fix typescript compilation errors in gcp-ts-functions

### ISSUE THREAD

**Issue by liftyourgame** [pulumi/examples#1289] opened 2022-10-02 22:09 UTC
### What happened?

Was getting typescript compilation errors relating to send not being on the Response object

### Steps to reproduce

Follow readme to setup: gcp-ts-functions project

### Expected Behavior

For the function to be deployed

### Actual Behavior

Running:
pulumi up

gives typescript compilation errors

### Additional context

Making these changes to packag.json seems to fix the problem.

```
--- a/gcp-ts-functions/package.json
+++ b/gcp-ts-functions/package.json
@@ -2,11 +2,13 @@
     "name": "gcp-ts-functions",
     "version": "2.0.0",
     "devDependencies": {
-        "@types/express": "^4.16.0",
-        "@types/node": "^12.0.0"
+        "@types/express": "^4.17.2",
+        "@types/express-serve-static-core": "^4.17.30",
+        "@types/node": "^18.8.0"
     },
     "dependencies": {
-        "@pulumi/gcp": "^5.0.0",
-        "@pulumi/pulumi": "^3.0.0"
+        "@pulumi/gcp": "^6.39.0",
+        "@pulumi/pulumi": "^3.40.2",
+        "typescript": "^4.1.6"
     }

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by scottslowe** [comment] 2022-11-04 17:52
@liftyourgame Thanks for taking the time to file this issue! We just merged some changes to fix a related issue (#1294), and I think it may have fixed your issue as I can't reproduce it. I'm going to go ahead and close this issue, but please feel free to re-open the issue if further action or discussion is needed.

**Closed by scottslowe** 2022-11-04 17:52 UTC
Labels: kind/bug, area/examples
