### ISSUE TITLE
Go s3 example throws errors

### ISSUE THREAD

**Issue by andy9775** [pulumi/examples#198] opened 2018-12-19 01:32 UTC
Hey copying the go s3 example from [here](https://github.com/pulumi/examples/tree/master/aws-go-s3-folder) throws the following errors.

```
vendor/github.com/pulumi/pulumi-aws/sdk/go/aws/s3/bucket.go:109:12: cannot use r.s.URN (type func() *pulumi.URNOutput) as type *pulumi.URNOutput in return argument
vendor/github.com/pulumi/pulumi-aws/sdk/go/aws/s3/bucket.go:114:12: cannot use r.s.ID (type func() *pulumi.IDOutput) as type *pulumi.IDOutput in return argument
vendor/github.com/pulumi/pulumi-aws/sdk/go/aws/s3/bucketMetric.go:58:12: cannot use r.s.URN (type func() *pulumi.URNOutput) as type *pulumi.URNOutput in return argument
vendor/github.com/pulumi/pulumi-aws/sdk/go/aws/s3/bucketMetric.go:63:12: cannot use r.s.ID (type func() *pulumi.IDOutput) as type *pulumi.IDOutput in return argument
vendor/github.com/pulumi/pulumi-aws/sdk/go/aws/s3/bucketNotification.go:61:12: cannot use r.s.URN (type func() *pulumi.URNOutput) as type *pulumi.URNOutput in return argument
vendor/github.com/pulumi/pulumi-aws/sdk/go/aws/s3/bucketNotification.go:66:12: cannot use r.s.ID (type func() *pulumi.IDOutput) as type *pulumi.IDOutput in return argument
vendor/github.com/pulumi/pulumi-aws/sdk/go/aws/s3/bucketObject.go:102:12: cannot use r.s.URN (type func() *pulumi.URNOutput) as type *pulumi.URNOutput in return argument
vendor/github.com/pulumi/pulumi-aws/sdk/go/aws/s3/bucketObject.go:107:12: cannot use r.s.ID (type func() *pulumi.IDOutput) as type *pulumi.IDOutput in return argument
vendor/github.com/pulumi/pulumi-aws/sdk/go/aws/s3/bucketPolicy.go:58:12: cannot use r.s.URN (type func() *pulumi.URNOutput) as type *pulumi.URNOutput in return argument
vendor/github.com/pulumi/pulumi-aws/sdk/go/aws/s3/bucketPolicy.go:63:12: cannot use r.s.ID (type func() *pulumi.IDOutput) as type *pulumi.IDOutput in return argument
vendor/github.com/pulumi/pulumi-aws/sdk/go/aws/s3/bucketPolicy.go:63:12: too many errors
```

In fact, any go examples that I tried running tends to throw the above errors(similar). Is this an known issue?

This also occurrs using github hooks (using the pulumi/hooks image) as well as locally.

**Comment by joshimhoff** [comment] 2019-04-08 18:55
+1

I've also run into this. Looks like a legit error? I can fix by removing the function call bit. Also looks like maybe this code was auto-generated?

**Comment by joshimhoff** [comment] 2019-04-10 15:09
I've realized the cause of this was API incompatibilities between the version of pulumi/pulumi and pulumi/pulumi-gcp I was using. I was able to fix it properly by doing some Gopkg.toml stuff.

**Comment by stack72** [comment] 2019-10-22 02:27
The Go test has been running successfully in CI so I am going to close this out - if this pops up again then we can reinvestigate

**Closed by stack72** 2019-10-22 02:27 UTC
