### ISSUE TITLE
gcp-ts-gke example failed with Error 403: Required "container.clusters.create" permission(s)

### ISSUE THREAD

**Issue by aidanbon** [pulumi/examples#150] opened 2018-10-07 22:50 UTC
I am following steps in the `gcp-ts-gke` example to create a GKE cluster via pulumi.

At `pulumi up`, I got stuck with the following error, complaining missing "container.clusters.create" permission(s) to my project:

```
% pulumi up
Previewing update of stack 'gcp-ts-gke-dev'
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE to remember):
Previewing changes:

     Type                            Name                       Plan          Info
 *   pulumi:pulumi:Stack             gcp-ts-gke-gcp-ts-gke-dev  no change
 +   ├─ gcp:container:Cluster        gke-cluster                create
 +   ├─ pulumi:providers:kubernetes  gkeK8s                     create
 +   └─ kubernetes:apps:Deployment   canary                     create

info: 3 changes previewed:
    + 3 resources to create
      1 resource unchanged

Do you want to perform this update? yes
Updating stack 'gcp-ts-gke-dev'
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE to remember):
Performing changes:

     Type                      Name                       Status                  Info
 *   pulumi:pulumi:Stack       gcp-ts-gke-gcp-ts-gke-dev  done
 +   └─ gcp:container:Cluster  gke-cluster                **creating failed**     1 error

Diagnostics:
  gcp:container:Cluster: gke-cluster
    error: Plan apply failed: googleapi: Error 403: Required "container.clusters.create" permission(s) for "projects/XXX"., forbidden

info: no changes required:
      1 resource unchanged
```

What did I miss? However, I can successfully create a cluster directly via gcloud CLI:

```
%  gcloud container clusters create my_cluster --zone us-west1-c --scopes storage-rw --machine-type n1-standard-2
```

**Comment by lukehoban** [comment] 2018-10-08 13:01
One potential cause of that error is attempting to create in a project you don't own, or don't have sufficient permissions to - see for example https://stackoverflow.com/questions/38173322/adding-permissions-to-a-project/38177381.

**Comment by aidanbon** [comment] 2018-10-09 05:32
Thanks @lukehoban, I'm pretty sure my  PROJECT ID is correct:
- confirmed from the GCP dashboard (https://console.cloud.google.com/home/dashboard),
-  also via the gcloud CLI (`gcloud config list project`).
- Again, in the same terminal, I can successfully spin up a GCP cluster directly via gcloud  CLI (`gcloud container clusters create my_cluster --zone us-west1-c --scopes storage-rw --machine-type n1-standard-2`)

However, when I repeat the steps inside **Google Cloud Shell,** everything (i.e. `pulumi up`) works as expected. Come back to my MacBook one more time, delete my ~/.pulumi and repeat the same steps:

- curl -fsSL https://get.pulumi.com | sh
- git clone https://github.com/pulumi/examples.git 
- cd examples
- npm i
- export GOOGLE_APPLICATION_CREDENTIALS=/Users/francis/Downloads/fay-517910d5931d.json
- pulumi login --local
- pulumi stack init gcp-ts-gke-dev
- pulumi config set gcp:project fay
- pulumi config set gcp:zone us-west1-c
- pulumi config set password --secret xxxxxxxxxxxxxxxx
- pulumi up

Same error 403 mentioned above re-appears. Since the same steps were successful inside Cloud Shell, this tells me either there are some env vars that I'm missing in my Mac env or the pulumi binary behaves differently between MacOS vs. Linux.

**Comment by lukehoban** [comment] 2018-11-26 00:40
I've tried to reproduce this several times, both on Mac and on Linux, and unfortunately have not been able to.

Most recently, I tried from a fully clean VM, following the exact steps listed in https://github.com/pulumi/examples/issues/150#issuecomment-428065214 (but replacing your project name `fay` with mine `pulumi-development`), and the program deployed successfully.

If I keep the project name as `fay`, I do indeed get the error message you see above, but that of course because the service account I am using does not have access to your project.  Given this error, I have to assume that somehow or another, the service account JSON file you reference in your example above does not actually provide you access to that project, or provides access with a service account that doesn't have the 
`container.clusters.create` permission.

I'd love to figure out what's going on here, but at this point I can't think of anything Pulumi-related that could be causing this.  If you are still having problems here and have any more data you could share though - I'd be happy to investigate further.

**Comment by sylv3r** [comment] 2018-12-02 22:38
Same issue here, it works with the owner account, but getting a private key to export from a custom service account raise 403 errors.

Does anyone know what are the roles actually needed to create a cluster on gcp ?
Having all the roles `roles/container.*` does not seem enough and Google docs are really not helpful at all.

**Comment by sylv3r** [comment] 2018-12-03 15:43
FYI I succeeded to create a cluster by exporting a key from the "Compute Engine default service account", but I don't like using it for such purpose, the permissions are too wide.
So I still don't really know what are the right permissions to give to a service account dedicated only to create a cluster.

**Comment by lukehoban** [comment] 2018-12-04 22:01
Re-opening, since folks continue to see problems here.  I unfortunately have not been able to reproduce in my own accounts, even after following the documented steps above, so I'm unsure what steps to suggest, and expect the underlying issue is something on the GKE side.  If anyone has tips on how to reproduce this issue, please let me know.

**Comment by sylv3r** [comment] 2018-12-05 09:44
@lukehoban I need to make a new run to be sure, but it feels like there was something wrong in the configuration indeed but not related to pulumi per se, or anything needing to be fix on your side.

In my numerous trials, I can now deploy a cluster from scratch with the right key in `GOOGLE_APPLICATION_CREDENTIALS`

In my case, for this purpose I have a manager service account with only the roles :

> Service Account Admin
> Service Account Key Admin
> Project IAM Admin

Who is then able to create within `pulumi` a specific service account dedicated to create and manage the cluster and which I use afterward in the `gcp` `provider` for all my resources.

**Comment by stack72** [comment] 2019-07-09 15:06
Hi all,

I am going to close this out - we have been successfully running this in our CI environment for a few weeks 

This is certainly an account configuration problem

If this is still a problem, then we can rethink this entire example

Thanks

Paul

**Closed by stack72** 2019-07-09 15:06 UTC

**Comment by nroberts1** [comment] 2020-08-03 09:31
I know this is closed but I got here so maybe others will too. I had 'Kubernetes Engine Developer' in my service account but got the above error until I added Kubernetes Engine Service Agent when trying to create a cluster from cli.

**Comment by metral** [comment] 2020-08-03 21:55
Thanks for the input @nroberts1.

Using `roles/container.clusterAdmin` is typically what would be used to provide the necessary permissions to create a cluster.

`developer` and `hostServiceAgentUser`  are lower access roles, so you'd need to combine them as you did to get success.

If you're already combining these roles, then `clusterAdmin` would not be far fetched.

See the predefined GKE roles in order of most permissions to least: https://cloud.google.com/kubernetes-engine/docs/how-to/iam

**Comment by deka** [comment] 2022-05-25 17:32
For me, if the zone is not in my list of authorized zones
